cc_binary(
    name = "WashingMachine",
    srcs = [
        "main.cpp",
    ],
    deps = [
        ":WashingMachineLib"
    ]
)

cc_library(
    name = "WashingMachineLib",
    srcs = [
        "WashingMachine.cpp"
    ],
    hdrs = [
        "WashingMachine.h"
    ],
)