cc_binary(
    name = "switch_case",
    srcs = ["switch_case.cpp"],
)

cc_binary(
    name = "table_driven",
    srcs = ["table.cpp"],
)

cc_binary(
    name = "state_pattern",
    srcs = ["state_pattern.cpp"],
)