cc_binary(
    name = "HtmlParserTest",
    srcs = [
        "main.cpp",
    ],
    deps = [
        ":HtmlParser"
    ]
)

cc_library(
    name = "HtmlParser",
    srcs = [
        "HtmlParser.cpp"
    ],
    hdrs = [
        "HtmlParser.h"
    ],
)